from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from gestion_patients.views import DossierEditView
from .views import PatientDeleteView

urlpatterns = [
       path('', views.accueil, name='accueil'),
       path('patients/', views.patient_list, name='patient_list'),
       path('patients/create/', views.patient_create, name='patient_create'),
       path('rdv/create/', views.rdv_create, name='rdv_create'),
       path('dossier/create/', views.dossier_create, name='dossier_create'),
       path('patients/edit/<int:pk>/', views.patient_edit, name='patient_edit'),
       path('patient/login/', views.patient_login, name='patient_login'),
       path('patients/<int:patient_id>/bon/create/', views.bon_assurance_create, name='bon_assurance_create'),
       path('bon/<int:bon_id>/validate/', views.bon_assurance_validate, name='bon_assurance_validate'),
       path('appointments/', views.appointment_list, name='appointment_list'),
       path('examens/', views.examen_resultat_list, name='examen_resultat_list'),
       path('patients/<int:patient_id>/verify/', views.patient_verify, name='patient_verify'),
       path('patient/login/', views.patient_login, name='patient_login'),
       path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
       path('bon/', views.bon_assurance_list, name='bon_assurance_list'),
       path('accounts/logout/', LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
       path('dossier/', views.consulter_dossier, name='consulter_dossier'),
       path('rdv/', views.gerer_rdv, name='gerer_rdv'),
    path('patients/enregistrer/', views.enregistrer_patient, name='enregistrer_patient'),
    path('bons_assurance/', views.consulter_bons_assurance, name='consulter_bons_assurance'),
    path('proforma/<int:proforma_id>/valider/', views.valider_proforma, name='valider_proforma'),
    path('resultat/edit/<int:pk>/', views.edit_resultat, name='edit_resultat'),
    path('resultat/delete/<int:pk>/', views.delete_resultat, name='delete_resultat'),
    path('examen_resultat/modifier/<int:pk>/', views.modifier_examen_resultat, name='modifier_examen_resultat'),
    path('resultat/edit/<int:pk>/', views.edit_resultat, name='edit_resultat'),
    path('dossiers/', views.dossier_patient, name='dossier_patient'),
    path('dossier/<int:pk>/edit/', DossierEditView.as_view(), name='dossier_edit'),
    path('rendez-vous/<int:pk>/edit/', views.rdv_edit, name='rdv_edit'),
    path('appointments/delete/<int:pk>/', views.delete_appointment, name='rdv_delete'),
    path('dossiers/ajouter/', views.dossier_form, name='dossier_form'),
     path('patients/<int:pk>/supprimer/', PatientDeleteView.as_view(), name='patient_delete'),
     path('proformas/', views.proforma_list, name='proforma_list'),
    path('proformas/create/', views.proforma_create, name='proforma_create'),
    path('proformas/<int:pk>/edit/', views.proforma_edit, name='proforma_edit'),
    path('proformas/<int:pk>/delete/', views.proforma_delete, name='proforma_delete'),
    path('resultats/create/', views.create_resultat, name='create_resultat'),
    path('dossiers/creer/', views.dossier_create, name='dossier_create'),
   path('dossiers/<int:pk>/supprimer/', views.dossier_delete, name='dossier_delete'), 
   ]
