# Generated by Django 5.2.3 on 2025-06-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patients', '0002_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonassurance',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='bonassurance',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Valide')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProForma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proforma', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('envoyé', 'Envoyé'), ('payé', 'Payé')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
