# Generated by Django 5.2.3 on 2025-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patients', '0003_remove_bonassurance_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proforma',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='numero_proforma',
        ),
        migrations.AlterField(
            model_name='proforma',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('rejeté', 'Rejeté'), ('payé', 'Payé')], default='brouillon', max_length=50),
        ),
    ]
