# Generated by Django 5.2.3 on 2025-06-26 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_patients', '0004_remove_proforma_montant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proforma',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
